CMAKE_MINIMUM_REQUIRED(VERSION 4.00)

PROJECT(RoguePlusPlus LANGUAGES CXX)

SET(CMAKE_CXX_STANDARD 23)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)
SET(CMAKE_CXX_EXTENSIONS OFF)
SET(CMAKE_EXPORT_COMPILE_COMMANDS ON)

SET(CURSES_NEED_WIDE true)

FIND_PACKAGE(PkgConfig REQUIRED)
FIND_PACKAGE(Curses REQUIRED)

# Create list of all *.cpp source files
FILE(GLOB ROGUE_SOURCES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")

ADD_COMPILE_OPTIONS(-Wall -Wextra -Wpedantic)
ADD_COMPILE_DEFINITIONS(MINROG)
ADD_COMPILE_DEFINITIONS(ROGUE_CHARSET=3)

ADD_EXECUTABLE(rogue++ ${ROGUE_SOURCES})

TARGET_INCLUDE_DIRECTORIES(rogue++ PRIVATE ${CURSES_INCLUDE_DIRS})
TARGET_LINK_LIBRARIES(rogue++ PRIVATE ${CURSES_LIBRARIES})
