CMAKE_MINIMUM_REQUIRED(VERSION 4.00)

PROJECT(RoguePlusPlus LANGUAGES C CXX ASM)

SET(CMAKE_C_STANDARD 17)

SET(CURSES_NEED_WIDE true)

FIND_PACKAGE(PkgConfig REQUIRED)
FIND_PACKAGE(Curses REQUIRED)

# Create list of all *.c source files
FILE(GLOB ROGUE_SOURCES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/*.c")

ADD_COMPILE_OPTIONS(-Wall -Wextra -Wpedantic)
ADD_COMPILE_DEFINITIONS(MINROG)
ADD_COMPILE_DEFINITIONS(ROGUE_CHARSET=3)
ADD_COMPILE_DEFINITIONS(ROGUE_NO_X11)

ADD_EXECUTABLE(rogue++ ${ROGUE_SOURCES})

TARGET_LINK_LIBRARIES(rogue++ PRIVATE ${CURSES_LIBRARIES})